name: "Send Adaptive Card Email"
description: 'Send GitHub Actions notifications to Email using SMTP authentication'
author: 'nshakya'
branding:
  icon: 'message-square'
  color: 'green'
inputs:
  github_token:
    description: Github token
    required: true
  smtp_server:
    description: "SMTP server address"
    required: true
  smtp_port:
    description: "SMTP server port"
    required: false
    default: "587"
  smtp_username:
    description: "SMTP username (email)"
    required: true
  smtp_password:
    description: "SMTP password"
    required: true
  from_email:
    description: "Sender email address"
    required: true
  to_email:
    description: "Recipient email address"
    required: true

  title:
    description: 'Notification Title'
    required: false
    default: 'GitHub Action Notification'
  status:
    description: 'Status (Success, Failure, Skipped, Cancelled, Unknown)'
    required: false
    default: 'Unknown'
  #files_changed:
  # description: 'List of changed files'
    #required: false
  environ: 
    description: 'Environment (e.g. dev, uat, prod)'
    required: false
  stage:
    description: 'Stage (e.g. build, test, deploy)'
    required: false
  app:
    description: 'Application Name (Your applcation name)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Run email script
      run: python ${{ github.action_path }}/send_email.py
      shell: bash
      env:
        SMTP_SERVER: ${{ inputs.smtp_server }}
        SMTP_PORT: ${{ inputs.smtp_port }}
        SMTP_USERNAME: ${{ inputs.smtp_username }}
        SMTP_PASSWORD: ${{ inputs.smtp_password }}
        FROM_EMAIL: ${{ inputs.from_email }}
        TO_EMAIL: ${{ inputs.to_email }}

        INPUT_GITHUB_TOKEN: ${{inputs.github_token}}
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_STATUS: ${{ inputs.status }}
        #INPUT_FILES_CHANGED: ${{ inputs.files_changed }}
        INPUT_ENVIRON: ${{inputs.environ}}
        INPUT_STAGE: ${{ inputs.stage }}
        INPUT_APP: ${{inputs.app}}   
