name: CI/CD Send Email

on:
  push:
    branches:
      - test-branch
  pull_request:
    branches:
      - test-branch
    types:
      - closed
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Adaptive Card Email
        uses: nerazshakya/Send-Email-Notification@main
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          smtp_server: ${{ vars.SMTP_SERVER }}
          smtp_port: ${{ vars.SMTP_PORT }}
          smtp_username: ${{ secrets.SMTP_USERNAME }}
          smtp_password: ${{ secrets.SMTP_PASSWORD }}
          from_email: ${{ vars.SENDER_EMAIL }}
          to_email: ${{ vars.RECEIVER_EMAIL }}
          title: ${{github.repository}}
          environ: 'DEV'
          app: 'MY APP'
          stage: 'Email'
          status: ${{ job.status }}


